# Generated by Django 5.2.8 on 2025-12-24 05:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("남", "남"), ("여", "여")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "marriage_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("미혼", "미혼"),
                            ("기혼", "기혼"),
                            ("사별", "사별"),
                            ("이혼", "이혼"),
                            ("기타", "기타"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("관리자", "관리자"),
                            ("전문가 및 관련 종사자", "전문가 및 관련 종사자"),
                            ("사무 종사자", "사무 종사자"),
                            ("서비스 종사자", "서비스 종사자"),
                            ("판매 종사자", "판매 종사자"),
                            ("농림어업 숙련 종사자", "농림어업 숙련 종사자"),
                            (
                                "기능원 및 관련 기능 종사자",
                                "기능원 및 관련 기능 종사자",
                            ),
                            (
                                "장치.기계 조작 및 조립 종사자",
                                "장치.기계 조작 및 조립 종사자",
                            ),
                            ("단순노무종사자", "단순노무종사자"),
                            ("군인", "군인"),
                            ("전업주부", "전업주부"),
                            ("학생", "학생"),
                            ("기타", "기타"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "income",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("소득없음", "소득없음"),
                            ("월평균 100만원 미만", "월평균 100만원 미만"),
                            (
                                "월평균 100만원 ~ 200만원 미만",
                                "월평균 100만원 ~ 200만원 미만",
                            ),
                            (
                                "월평균 200만원 ~ 300만원 미만",
                                "월평균 200만원 ~ 300만원 미만",
                            ),
                            (
                                "월평균 300만원 ~ 400만원 미만",
                                "월평균 300만원 ~ 400만원 미만",
                            ),
                            (
                                "월평균 400만원 ~ 500만원 미만",
                                "월평균 400만원 ~ 500만원 미만",
                            ),
                            (
                                "월평균 500만원 ~ 600만원 미만",
                                "월평균 500만원 ~ 600만원 미만",
                            ),
                            (
                                "월평균 600만원 ~ 700만원 미만",
                                "월평균 600만원 ~ 700만원 미만",
                            ),
                            (
                                "월평균 700만원 ~ 800만원 미만",
                                "월평균 700만원 ~ 800만원 미만",
                            ),
                            (
                                "월평균 800만원 ~ 900만원 미만",
                                "월평균 800만원 ~ 900만원 미만",
                            ),
                            (
                                "월평균 900만원 ~ 1,000만원 미만",
                                "월평균 900만원 ~ 1,000만원 미만",
                            ),
                            ("월평균 1,000만원 이상", "월평균 1,000만원 이상"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("travel_num", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "residence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("서울특별시", "서울특별시"),
                            ("경기도", "경기도"),
                            ("인천광역시", "인천광역시"),
                            ("대전광역시", "대전광역시"),
                            ("충청북도", "충청북도"),
                            ("충청남도", "충청남도"),
                            ("광주광역시", "광주광역시"),
                            ("전라북도", "전라북도"),
                            ("전라남도", "전라남도"),
                            ("울산광역시", "울산광역시"),
                            ("대구광역시", "대구광역시"),
                            ("부산광역시", "부산광역시"),
                            ("경상북도", "경상북도"),
                            ("경상남도", "경상남도"),
                            ("강원도", "강원도"),
                            ("제주특별자치도", "제주특별자치도"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_setting", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
