# Generated by Django 5.2.8 on 2025-12-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routeplace",
            name="place_id",
        ),
    ]
